version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bgn?sslmode=disable
    depends_on:
      - db
    restart: unless-stopped
